export const MAINSTACK = {
  HOMENAVIGATION: 'HOMENAVIGATION',
  AUTHNAVIGATION: 'AUTHNAVIGATION',
  DUMMYStack: 'DUMMYStack',
  SPLASHSCREEN: 'SPLASHSCREEN',
};

export const AUTH = {
  SIGNUP: 'SIGNUP',
  VERIFICATION: 'VERIFICATION',
  SIGNIN: 'SIGNIN',
  FORGOTPASSWORD: 'FORGOTPASSWORD',
  ONBOARDING: 'ONBOARDING',
};

export const HOME = {
  DASHBOARD: 'DASHBOARD',
  BOTTOMTABS: 'BOTTOMTABS',
  HOME: 'HOME',
  DOCTORNEARYOU: 'DOCTORNEARYOU',
  OFFERPAGE: 'OFFERPAGE',
  APPOINTMENTPAGE: 'APPOINTMENTPAGE',
  PROFILEPAGE: 'PROFILEPAGE',
};
export const DASHBOARD = {
  SEARCHPAGE: 'SEARCHPAGE',
  DOCTORS: 'DOCTORS',
  DOCTORDETAILS: 'DOCTORDETAILS',
  SELECTTIME: 'SELECTTIME',
};
