export const AUTH = {
  SIGNUP: 'SIGNUP',
  SIGNIN: 'SIGNIN',
  ONBOARDING: 'ONBOARDING',
};

export const LANDING = {
  SPLASHSCREEN: 'SPLASHSCREEN',
};
export const HOME = {
  DASHBOARD: 'DASHBOARD',
  HOME: 'HOME',
  DOCTORNEARYOU: 'DOCTORNEARYOU',
  OFFERPAGE: 'OFFERPAGE',
  CARTPAGE: 'CARTPAGE',
  PROFILEPAGE: 'PROFILEPAGE',
};
