export const AUTH = {
  SIGNUP: 'SIGNUP',
  SIGNIN: 'SIGNIN',
  ONBOARDING: 'ONBOARDING',
};

export const LANDING = {
  SPLASHSCREEN: 'SPLASHSCREEN',
};
export const HOME = {
  DASHBOARD: 'DASHBOARD',
  BOTTOMTABS: 'BOTTOMTABS',
  HOME: 'HOME',
  DOCTORNEARYOU: 'DOCTORNEARYOU',
  OFFERPAGE: 'OFFERPAGE',
  CARTPAGE: 'CARTPAGE',
  PROFILEPAGE: 'PROFILEPAGE',
};
export const DASHBOARD = {
  SEARCPAGE: 'SEARCPAGE',
  SELECTTIME: 'SELECTTIME',
};
