
default_platform(:android)

platform :android do
  desc "Run Android unit tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build Android APK (Debug)"
  lane :build_debug do
    gradle(
      task: "assembleDebug",
      build_type: "Debug"
    )
  end

  desc "Build Android APK (Release)"
  lane :build_release do
    gradle(
      task: "clean assembleRelease"
    )
  end
end


platform :ios do
  desc "Build iOS for simulator (no signing needed)"
  lane :build_simulator do
    build_app(
      scheme: "doctor_app",
      sdk: "iphonesimulator",
      configuration: "Debug",
      export_method: "development",
      skip_package_ipa: true,
      skip_codesigning: true,
      destination: "generic/platform=iOS Simulator"
    )
  end

  desc "Build iOS Release IPA"
  lane :build_release do
    build_app(
      scheme: "doctor_app",
      export_method: "ad-hoc", # or app-store, development
      output_directory: "build",
      output_name: "doctor_app.ipa"
    )
  end
end