default_platform(:ios)

platform :ios do
  desc "Build for simulator (no signing needed)"
  lane :build_simulator do
    build_app(
      scheme: "doctor_app", # replace with your scheme name
      sdk: "iphonesimulator",
      export_method: "development",
      skip_codesigning: true
    )
  end

  desc "Run iOS tests"
  lane :tests do
    scan(
      scheme: "doctor_app",
      devices: ["iPhone 15"],
      clean: true
    )
  end
end
