
default_platform(:android)

platform :android do
  desc "Run Android unit tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build Android APK (Debug)"
  lane :build_debug do
    gradle(
      task: "assembleDebug",
      build_type: "Debug"
    )
  end

  desc "Build Android APK (Release)"
  lane :build_release do
    gradle(
      task: "clean assembleRelease",
      build_type: "Release"
    )
  end
end
